name: y_infra
description: A reusable Flutter infrastructure package — cache, storage, auth, network, database, permissions, formatters, and more.
version: 0.0.2

topics:
  - infrastructure
  - architecture
  - utilities

environment:
  sdk: ^3.5.4
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.2.0
  dio: ^5.4.0
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.2.0
  uuid: ^4.4.0
  url_launcher: ^6.2.0
  easy_localization: ^3.0.0
  intl: ^0.20.0
  permission_handler: ^12.0.0
  http: ^1.6.0
  path_provider: ^2.1.0
  csv: ^6.0.0
  geolocator: ^14.0.0
  string_validator: ^1.1.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.0
  sqflite: ^2.4.0
  firebase_core: ^4.6.0
  firebase_analytics: ^12.2.0
  firebase_messaging: ^16.1.0
  firebase_database: ^12.2.0
  awesome_notifications: ^0.11.0
  flutter_dotenv: ^6.0.0
  connectivity_plus: ^6.1.0
